name: Image Deployment

on:
  workflow_run:
    workflows: ["Liatrio Apprentice Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

        - name: prepare ssh key
          run: |
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.SSH_IP }} > ~/.ssh/known_hosts

        - name: update server
          run: ssh  ubuntu@${{ secrets.SSH_IP }} "sudo docker stop myinstance && sudo docker rm myinstance && sudo docker pull gdsmith1/liatrio-demo && sudo docker run -p 80:80 --name myinstance -d gdsmith1/liatrio-demo:latest"

        - name: check container running
          run: |
                sleep 10 # time for container to start up
                ssh ubuntu@${{ secrets.SSH_IP }} "sudo docker ps"
                curl -v http://${{ secrets.SSH_IP }}:80

        - name: Cleanup ssh key
          run: rm -rf ~/.ssh
