name: Image Deployment

on:
  workflow_run:
    workflows: ["Liatrio Apprentice Tests"]
    types:
      - completed
  push:
    branches: [ "docker-upload" ]

jobs:
  second_job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: update server
          run: |
                echo "${{ secrets.SSH_KEY }}" > ssh_key.pem
                chmod 400 ssh_key.pem
                ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts
                ssh  -i ssh_key.pem -o StrictHostKeyChecking=yes ubuntu@${{ secrets.SSH_IP }} "docker pull gdsmith1/liatrio-demo && docker run -p 80:80 --name myinstance -d gdsmith1/liatrio-demo:latest"

        - name: check container running
          run: |
                sleep 10 # time for container to start up
                ssh -i ssh_key.pem ubuntu@${{ secrets.SSH_IP }} "docker ps"
                curl -v http://${{ secrets.SSH_IP }}:80