name: Liatrio Apprentice Tests

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Build the Docker image
          run: docker build -t jstest .



    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Start Docker container
          run: docker run -p 80:80 --name myinstance -d jstest

        - name: check container running
          run: |
                sleep 10 # give server time to start
                docker ps
                curl -v http://127.0.0.1:80

        - name: run tests
          uses: liatrio/github-actions/apprentice-action@master



    cleanup:
        needs: test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: End Docker container
          run: |
                docker stop myinstance
                docker rm myinstance
