name: Liatrio Apprentice Tests

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Build the Docker image
          run: docker build -t jstest .
        - name: Save Docker image to a tar file
          run: docker save -o jstest.tar jstest

        - name: Upload Docker image to artifacts
          uses: actions/upload-artifact@v2
          with:
            name: jstest
            path: jstest.tar



    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Download Docker image from artifacts
          uses: actions/download-artifact@v2
          with:
            name: jstest
            path: /tmp

        - name: Load Docker image from tar file
          run: docker load -i /tmp/jstest.tar

        - name: Start Docker container
          run: docker run -p 80:80 --name myinstance -d jstest

        - name: check container running
          run: |
                sleep 5
                docker ps
                curl -v http://127.0.0.1:80

        - name: run tests
          uses: liatrio/github-actions/apprentice-action@v1.0.0

        - name: End Docker container
          run: |
                docker stop myinstance
                docker rm myinstance

    upload:
        needs: test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Download Docker image from artifacts
          uses: actions/download-artifact@v2
          with:
            name: jstest
            path: /tmp

        - name: Load Docker image from tar file
          run: docker load -i /tmp/jstest.tar

        
