name: Liatrio Apprentice Tests

on:
    push:
      branches: [ "main"]
    pull_request:
      branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Build the Docker image
          run: docker build -t gdsmith1/liatrio-demo .
        - name: Save Docker image to a tar file
          run: docker save -o liatriodemo.tar gdsmith1/liatrio-demo

        - name: Upload Docker image to artifacts
          uses: actions/upload-artifact@v4
          with:
            name: docker-image
            path: liatriodemo.tar



    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Download Docker image from artifacts
          uses: actions/download-artifact@v4
          with:
            name: docker-image
            path: /tmp

        - name: Load Docker image from tar file
          run: docker load -i /tmp/liatriodemo.tar

        - name: Start Docker container
          run: docker run -p 80:80 --name myinstance -d gdsmith1/liatrio-demo

        - name: check container running
          run: |
                sleep 10 # time for container to start up
                docker ps
                curl -v http://127.0.0.1:80

        - name: run tests
          uses: liatrio/github-actions/apprentice-action@v1.0.0

        - name: End Docker container
          run: |
                docker stop myinstance
                docker rm myinstance

    upload:
        needs: test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Download Docker image from artifacts
          uses: actions/download-artifact@v4
          with:
            name: docker-image
            path: /tmp

        - name: Load Docker image from tar file
          run: docker load -i /tmp/liatriodemo.tar

        - name: Docker login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Push image
          run: docker push gdsmith1/liatrio-demo
