name: Liatrio Apprentice Tests

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: docker build -t jstest .

        - name: Start Docker container
          run: docker run -p 80:80 --name myinstance -d jstest

        - name: run tests
          uses: liatrio/github-actions/apprentice-action@master

        - name: End Docker container
          run: |
                docker stop myinstance
                docker rm myinstance
