name: Liatrio Apprentice Tests

on:
  workflow_run:
    workflows:
      - "Docker Image CI"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
